### ISSUE TITLE
Allow user to choose final download directory

### ISSUE THREAD

**Issue by hivanov-nrel** [DAP-platform/dap-py#1]
Currently, the download function appends the dataset name to the download path provided by the user. It would be nice for the user to have full control of where the data gets downloaded. 

Fix by setting `download_dir = path` on line 358 (for instance)

**Comment by mkieburtzpnnl** [comment]
Definitely a good idea. Fixed in d9d3a0b25a7872c8a10b521916ada9829fba5ee0
