### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by maxwellevin** [DAP-platform/dap-py#5]
It is generally a best practice to include a `requirements.txt` file at the top level of the repository when 3rd party dependencies are used in the package.

Here the plotting part of dap-py says it requires `numpy` and `matplotlib`, so I would recommend adding these to a `requirements.txt` file. Anyone who clones this repository can then run `pip install -r requirements.txt` to install `numpy` and `matplotlib`. If you are creating a python package, then these can also be included in your setup.py file and when users run `pip install dap_py` they will also get these extra requirements.

**Comment by maxwellevin** [comment]
Making extra requirements optional for the pip package is not too tricky either, if you are thinking that you'd rather not have users install extras by default: See [python packaging extras / optional dependencies](https://youtu.be/q78-YoId6Fk) for a tutorial

**Comment by mkieburtzpnnl** [comment]
Added in 3bc40c7b0d2bb6ac6353c2e93978ebc9c27366c1
