### ISSUE TITLE
update documentation to include ext1 example

### ISSUE THREAD

**Issue by mmacduff** [DAP-platform/dap-py#6]

**Comment by mmacduff** [comment]
update documentation to include ext1 example

filter = {
    'Dataset': 'wfip2/lidar.z01.b0',
    'date_time': {
        'between': ['20160101000000', '20160104000000']
    },
    'ext1': 'sta',
    'ext5': 'nrel',
    'ext18': 'good',
    'file_type': 'nc'
}

**Comment by mkieburtzpnnl** [comment]
Added in 6dad1ac09b05b6395f4d1ddbf977a4c896f082d1, albeit with a different example.
